Orderer:
  OrdererType: kafka
  Addresses:
    &a9
    - orderer0.cache.com:7050
    - orderer1.cache.com:7050
    - orderer2.cache.com:7050
    - orderer3.cache.com:7050
    - orderer4.cache.com:7050
  BatchTimeout: 5s
  BatchSize:
    &a10
    MaxMessageCount: 1200
    AbsoluteMaxBytes: 50 MB
    PreferredMaxBytes: 10 MB
  Kafka:
    &a11
    Brokers: []
  Organizations:
    &a12
    - &a6
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/cache.com/msp
Capabilities:
  Channel:
    &a2
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer:
    &a7
    V1_4_2: true
    V1_1: false
  Application:
    &a1
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false
Application:
  &a14
  Organizations: {}
  Capabilities: *a1
Channel:
  Capabilities: *a2
Organizations:
  - &a13
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/cache.com/msp
  - &a3
    Name: usersMSP
    ID: usersMSP
    MSPDir: crypto-config/peerOrganizations/users.com/msp
    AnchorPeers:
      - Host: peer0.users.com
        Port: 7051
  - &a4
    Name: companiesMSP
    ID: companiesMSP
    MSPDir: crypto-config/peerOrganizations/companies.com/msp
    AnchorPeers:
      - Host: peer0.companies.com
        Port: 7051
  - &a5
    Name: exchangesMSP
    ID: exchangesMSP
    MSPDir: crypto-config/peerOrganizations/exchanges.com/msp
    AnchorPeers:
      - Host: peer0.exchanges.com
        Port: 7051
Profiles:
  Channel:
    Consortium: AutoblockConsortium
    Application:
      Organizations:
        &a8
        - *a3
        - *a4
        - *a5
  OrdererGenesis:
    Orderer:
      Organizations: *a6
      Capabilities: *a7
    Consortiums:
      AutoblockConsortium:
        Organizations: *a8
  DevModeKafka:
    Capabilities: *a2
    Orderer:
      OrdererType: kafka
      Addresses: *a9
      BatchTimeout: 5s
      BatchSize: *a10
      Kafka: *a11
      Organizations: *a12
      Capabilities: *a7
    Application:
      Organizations:
        - *a13
      Capabilities: *a1
    Consortiums:
      AutoblockConsortium:
        Organizations: *a8
  MultiNodeEtcdRaft:
    Capabilities:
      V1_4_3: true
      V1_3: false
      V1_1: false
    Orderer:
      OrdererType: etcdraft
      Addresses: *a9
      BatchTimeout: 5s
      BatchSize: *a10
      Kafka: *a11
      Organizations:
        - *a13
      EtcdRaft:
        Consenters:
          - Host: orderer0.cache.com
            Port: "7050"
            ClientTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer0.cache.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer0.cache.com/tls/server.crt
          - Host: orderer1.cache.com
            Port: "7050"
            ClientTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer1.cache.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer1.cache.com/tls/server.crt
          - Host: orderer2.cache.com
            Port: "7050"
            ClientTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer2.cache.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer2.cache.com/tls/server.crt
          - Host: orderer3.cache.com
            Port: "7050"
            ClientTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer3.cache.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer3.cache.com/tls/server.crt
          - Host: orderer4.cache.com
            Port: "7050"
            ClientTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer4.cache.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/cache.com/orderers/orderer4.cache.com/tls/server.crt
      Capabilities: *a7
    Application: *a14
    Consortiums:
      AutoblockConsortium:
        Organizations: *a8
