OrdererOrgs:
  - Name: Orderer
    Domain: cache.com
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
PeerOrgs:
  - Name: users
    Domain: users.com
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 1
  - Name: companies
    Domain: companies.com
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 1
  - Name: exchanges
    Domain: exchanges.com
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 1
